table Calendar
	dataCategory: Time
	lineageTag: 4d7f6dfb-03c2-43e5-a150-e2162fd049b1

	column 'Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: dad2e66e-8da4-4ed1-9423-040dfa4fa66c
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fafb6c18-f190-4cec-82d4-54e1017f040e
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ef3cfc8f-5e58-427a-9256-fa39e5b6ead0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: c8b1ef8c-12a5-4eaf-b0d4-ad0c23a29fe4
		summarizeBy: none
		sourceColumn: Month Number
		isHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 82afea66-55ea-4359-9c78-0e7076032584
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month Number'

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: 1e26bc3d-f514-483e-b8b5-3c1650798aac
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column 'Period Type' = IF ( 'Calendar'[Date] <= MAX ( Sales[Order Date] ), "Actual", "Forecast" )
		dataType: string
		lineageTag: 4a7109c6-74f8-4694-bc95-9cad75e7f531
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: import
		source =
				let
				    StartDate = #date(2025, 1, 1),
				    EndDate = #date(2026, 12, 31),
				    Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    AsTable = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    Typed = Table.TransformColumnTypes(AsTable, {{"Date", type date}}),
				    AddYear = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
				    AddQuarter = Table.AddColumn(AddYear, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    AddMonthNumber = Table.AddColumn(AddQuarter, "Month Number", each Date.Month([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddMonthNumber, "Month", each Date.ToText([Date], "MMM", "en-US"), type text),
				    AddYearMonth = Table.AddColumn(AddMonth, "Year Month", each Date.ToText([Date], "yyyy-MM", "en-US"), type text)
				in
				    AddYearMonth

	annotation PBI_ResultType = Table

