table Customers
	lineageTag: 13d94ad0-d809-4e6d-b41a-d2c25ceef79c

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: 6086a5f3-e594-4c30-b458-30d691c0e6c0
		summarizeBy: none
		sourceColumn: Customer ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 3c9b7cd1-983e-4d3b-b176-6ffc05fbd075
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 16440645-f17a-4355-85b3-f11620629446
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b39844f4-e194-4b21-ae7e-2fbc21f8b225
		summarizeBy: none
		sourceColumn: Region
		isHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 745d8729-5bc7-4822-bcfe-06e3c395899e
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Customers.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Customer ID", Int64.Type}, {"Customer", type text}, {"Segment", type text}, {"Region", type text}, {"Country", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

