table Products
	lineageTag: fc947bc1-d14f-48aa-9cdd-1043ba80c88b

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: b2e9da66-1bd5-42b4-9336-79f28ccf8851
		summarizeBy: none
		sourceColumn: Product ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 9ace5bb2-bcf8-4f7f-b80f-52f39a870bf7
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b36203ce-7646-4493-a091-86d63990d711
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: \$#,0.00
		lineageTag: 7e460b4e-c213-49d9-bdc6-42fe2872edca
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost'
		dataType: double
		formatString: \$#,0.00
		lineageTag: 1646113d-dc76-49e5-8a79-9c752e206e6f
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Products.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Product ID", Int64.Type}, {"Product", type text}, {"Category", type text}, {"Unit Price", type number}, {"Unit Cost", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

