table Products
	lineageTag: e5d0111f-8521-46cd-8e30-0e9c8edb0ef1

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: 78f45889-1e49-476a-90d5-2b99a2a1a620
		summarizeBy: none
		sourceColumn: Product ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a910c002-ae9f-441d-beb8-bf0b8775a0f0
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9d470a35-c816-4c27-bc3c-4c2fa40e0199
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: \$#,0.00
		lineageTag: 5ef993c3-07d7-4fec-9d34-a21912990cb3
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost'
		dataType: double
		formatString: \$#,0.00
		lineageTag: 2e3c7679-6dc2-47db-9763-7e6ccd87a06a
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Products.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Product ID", Int64.Type}, {"Product", type text}, {"Category", type text}, {"Unit Price", type number}, {"Unit Cost", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

