table Sales
	lineageTag: 509ac91f-31ea-41f4-a364-8766a43a4bdd

	measure 'Total Sales' = SUMX ( Sales, Sales[Quantity] * Sales[Unit Price] * ( 1 - Sales[Discount] ) )
		formatString: \$#,0
		displayFolder: Revenue
		lineageTag: 8c38c18b-02de-4556-9f27-e8b562e03868

	measure 'Total Cost' = SUMX ( Sales, Sales[Quantity] * RELATED ( Products[Unit Cost] ) )
		formatString: \$#,0
		displayFolder: Revenue
		lineageTag: 30794bd3-4ba4-48a8-915d-4c4315678e9b

	measure 'Gross Profit' = [Total Sales] - [Total Cost]
		formatString: \$#,0
		displayFolder: Revenue
		lineageTag: 17caf26b-cbfe-4d65-a23b-34635f6763a6

	measure 'Profit Margin %' = DIVIDE ( [Gross Profit], [Total Sales] )
		formatString: 0.0%
		displayFolder: Revenue
		lineageTag: b97938ac-ead2-4702-8fcc-588e49ec6e32

	measure Orders = DISTINCTCOUNT ( Sales[Order ID] )
		formatString: #,0
		displayFolder: Volume
		lineageTag: 4a13b17c-8d93-4a1b-a5d2-5bc33c3826aa

	measure 'Units Sold' = SUM ( Sales[Quantity] )
		formatString: #,0
		displayFolder: Volume
		lineageTag: 3e74ba44-a65e-4003-91bf-4361edb5db91

	measure 'Avg Order Value' = DIVIDE ( [Total Sales], [Orders] )
		formatString: \$#,0
		displayFolder: Volume
		lineageTag: 96f22a06-15c5-4e34-b183-0345a4229f14

	measure 'Avg Selling Price' = DIVIDE ( [Total Sales], [Units Sold] )
		formatString: \$#,0.00
		displayFolder: Volume
		lineageTag: c9425b82-0c20-4760-814f-5b9f82a54c56

	measure 'Sales PY' = CALCULATE ( [Total Sales], SAMEPERIODLASTYEAR ( 'Calendar'[Date] ) )
		formatString: \$#,0
		displayFolder: Time Intelligence
		lineageTag: c87533e5-6bcf-476f-86bf-c38b7b8ae091

	measure 'Sales YoY %' = DIVIDE ( [Total Sales] - [Sales PY], [Sales PY] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: 8ce285db-db30-4078-8435-0ad5c04675c7

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: fb81519b-ddc9-49b0-a89e-77e54f304094
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ad20c3fa-d501-48d7-90ff-14bf96b525c7
		summarizeBy: none
		sourceColumn: Order Date
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: 00ef3377-08ed-4047-9900-1fc9ca445a6b
		summarizeBy: none
		sourceColumn: Customer ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: fe9d21c3-c5e9-4866-bbbb-dbd132d48c82
		summarizeBy: none
		sourceColumn: Product ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: c068a64c-d5d6-4a82-b500-d6ef0453ab6d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: \$#,0.00
		lineageTag: 00e5ebaf-2eb0-4b1e-aa7e-ee0b677ebe4d
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: 0%
		lineageTag: 47691dcb-d0c9-4fc1-913f-24955ebc23bf
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Sales.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Order ID", Int64.Type}, {"Order Date", type date}, {"Customer ID", Int64.Type}, {"Product ID", Int64.Type}, {"Quantity", Int64.Type}, {"Unit Price", type number}, {"Discount", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

